version: "3.7"
services:
  app:
    build:
      args:
        user: appusr
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: app-image
    container_name: appcontainer
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ../:/var/www
    networks:
      - app-net

  nginx:
    image: nginx:1.17-alpine
    container_name: app-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
